namespace: tap-dev
targetImagePullSecret: "registry-credentials"
snyk:
  tokenSecret:
    name: snyk-token-secret
metadataStore:
  url: "https://metadata-store.tanzu.y-compiles.com"
  caSecret:
    importFromNamespace: ""
  authSecret:
    importFromNamespace: ""