#@ load("@ytt:data", "data")
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: tanzu-system-ingress
spec:
  acme:
    email: yunusa.namadi@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - http01:
        ingress:
          class: contour
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: y-compiles.com
  namespace: tanzu-system-ingress
spec:
  secretName: tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - '*.tanzu.y-compiles.com'
  - harbor.y-compiles.com