#@data/values

#@overlay/match-child-defaults missing_ok=True
---
tap:
  version: "1.1.2"
  namespace: tap-install
  catalogs: []

  registry:
    host: harbor.tanzu.projectscions.com
    repositories:
      buildService: repo/build-service
      ootbSupplyChain: repo/supply-chain

  domains:
    main: projectscions.com
    tapGui: tap-gui.projectscions.com
