#@data/values

#@overlay/match-child-defaults missing_ok=True
---
tap:
  version: "1.4.0-build.20"
  namespace: tap-install
  catalogs: []

  registry:
    host: tapbuild.azurecr.io
    repositories:
      buildService: tap/build-service
      ootbSupplyChain: tanzu-application-platform

  domains:
    main: tap.tanzu.y-compiles.com
    tapGui: tap-gui.tap.tanzu.y-compiles.com
