#@data/values

#@overlay/match-child-defaults missing_ok=True
---
tap:
  version: "1.3.0-build.23"
  namespace: tap-install
  catalogs: []

  registry:
    host: tapbuild.azurecr.io
    repositories:
      buildService: tap/build-service
      ootbSupplyChain: tap/supply-chain

  domains:
    main: tanzu.y-compiles.com
    tapGui: tap-gui.tanzu.y-compiles.com
