#@data/values

#@overlay/match-child-defaults missing_ok=True
---
tap:
  version: "1.5.0-rc.16"
  namespace: tap-install
  catalogs: []

  registry:
    host: tapbuild.azurecr.io
    repositories:
      buildService: repo/build-service
      ootbSupplyChain: repo/supply-chain

  domains:
    main: tap.tanzu.y-compiles.com
    tapGui: tap-gui.tap.tanzu.y-compiles.com
