#@data/values

#@overlay/match-child-defaults missing_ok=True
---
tap:
  devNamespace: tap-dev

  domains:
    learningCenter: learningcenter.y-compiles.com
    knative: apps.y-compiles.com
    appliveview:
          host: appliveview.y-compiles.com
          port: 443

domain: y-compiles.com
tls:
  secretName: tls
  namespace: tanzu-system-ingress