#@data/values

#@overlay/match-child-defaults missing_ok=True
---
tap:
  devNamespace: dev-ns

  domains:
    learningCenter: learningcenter.tanzu.projectscions.com
    knative: apps.projectscions.com

domain: projectscions.com
tls:
  secretName: tls
  namespace: tanzu-system-ingress