#@data/values

#@overlay/match-child-defaults missing_ok=True
---
tap:
  devNamespace: tap-dev

  domains:
    learningCenter: learningcenter.tanzu.y-compiles.com
    knative: apps.tanzu.y-compiles.com

domain: y-compiles.com
tls:
  secretName: tls
  namespace: tanzu-system-ingress