#@data/values

#@overlay/match-child-defaults missing_ok=True
---
tap:
  devNamespace: tap-dev

  domains:
    learningCenter: learningcenter.tap.tanzu.y-compiles.com
    knative: apps.tap.tanzu.y-compiles.com

domain: tap.tanzu.y-compiles.com
tls:
  secretName: tls
  namespace: tanzu-system-ingress